### ISSUE TITLE
Add avro plugin

### ISSUE THREAD

**Issue by aalmiray** [aalmiray/gradle-plugins#23]
Located at https://github.com/iamsteveholmes/avro-gradle-plugin

**Comment by davidmc24** [comment]
There's also mine in this space.  Do you have any thoughts on how best to handle cases where there are multiple plugins for a single thing?

https://github.com/commercehub-oss/gradle-avro-plugin

**Comment by aalmiray** [comment]
Ahh well, no, haven't given much thought about it yet. I suppose that the plugin with most features gets listed first. Other qualifications for inclusion in the portal may be 
- is it active
- is it current (works with gradle 1.10+ for example)
- is it available from a public repo (i.e, mavenCentral || jcenter)
