### ISSUE TITLE
Add GnuMake plugin

### ISSUE THREAD

**Issue by ysb33r** [aalmiray/gradle-plugins#65]
Hosted at 

https://github.com/ysb33r/Gradle/tree/master/gnumake

**Comment by aalmiray** [comment]
The following script

```
buildscript {
    repositories {
        maven { url 'http://dl.bintray.com/ysb33r/grysb33r' }
    }
    dependencies {
        classpath 'org.ysb33r.gradle:gradle-gnumake-plugin:0.0.3'
    }
}

import org.ysb33r.gradle.gnumake.GnuMakeBuild

task runMake (type:GnuMakeBuild) {
    targets = ['build','install']
    flags = [ DESTDIR : '/copy/files/here', BUILD_NUMBER : 12345 ]
}
```

throws a build exception

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'test'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find org.ysb33r.gradle:gradle-gnumake-plugin:0.0.3.
     Required by:
         :test:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.199 secs
```

**Comment by ysb33r** [comment]
Oh F#$%@k. I'l look into it right now.

On 05/03/2014 20:25, Andres Almiray wrote:

> The following script
> 
> |buildscript {
>      repositories {
>          maven { url 'http://dl.bintray.com/ysb33r/grysb33r' }
>      }
>      dependencies {
>          classpath 'org.ysb33r.gradle:gradle-gnumake-plugin:0.0.3'
>      }
> }
> 
> import org.ysb33r.gradle.gnumake.GnuMakeBuild
> 
> task runMake (type:GnuMakeBuild) {
>      targets = ['build','install']
>      flags = [ DESTDIR : '/copy/files/here', BUILD_NUMBER : 12345 ]
> }
> |
> 
> throws a build exception
> 
> |FAILURE: Build failed with an exception.
> - What went wrong:
>   A problem occurred configuring root project 'test'.
>   
>   > Could not resolve all dependencies for configuration ':classpath'.
>   > Could not find org.ysb33r.gradle:gradle-gnumake-plugin:0.0.3.
>   >   Required by:
>   >       :test:unspecified
> - Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 1.199 secs
> |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/aalmiray/gradle-plugins/issues/65#issuecomment-36789116.

## 

Schalk W. Cronjé
@ysb33r

**Comment by aalmiray** [comment]
Linking your grysb33r repo (or at least the gradle plugins) to JCenter will enable anyone to use the `jcenter()` block on their gradle scripts :wink:

**Comment by ysb33r** [comment]
The documentation was incorrect. It is now fixed. Leaving this one 
outside of jCenter() for now.

Should have read:

buildscript {
   repositories {
     ivy {
       url 'http://dl.bintray.com/ysb33r/grysb33r'
     }
   }
   dependencies {
     classpath 'org.ysb33r.gradle:gnumake:0.0.9'
   }
}

On 05/03/2014 20:25, Andres Almiray wrote:

> The following script
> 
> |buildscript {
>      repositories {
>          maven { url 'http://dl.bintray.com/ysb33r/grysb33r' }
>      }
>      dependencies {
>          classpath 'org.ysb33r.gradle:gradle-gnumake-plugin:0.0.3'
>      }
> }
> 
> import org.ysb33r.gradle.gnumake.GnuMakeBuild
> 
> task runMake (type:GnuMakeBuild) {
>      targets = ['build','install']
>      flags = [ DESTDIR : '/copy/files/here', BUILD_NUMBER : 12345 ]
> }
> |
> 
> throws a build exception
> 
> |FAILURE: Build failed with an exception.
> - What went wrong:
>   A problem occurred configuring root project 'test'.
>   
>   > Could not resolve all dependencies for configuration ':classpath'.
>   > Could not find org.ysb33r.gradle:gradle-gnumake-plugin:0.0.3.
>   >   Required by:
>   >       :test:unspecified
> - Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 1.199 secs
> |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/aalmiray/gradle-plugins/issues/65#issuecomment-36789116.

## 

Schalk W. Cronjé
@ysb33r

**Comment by aalmiray** [comment]
Unfortunately it keeps crashing on my side with gradle 1.11; same error even with the updated config :cry:

**Comment by aalmiray** [comment]
So just to be on the same page, this is what I tried

```
buildscript {
  repositories {
    ivy { url 'http://dl.bintray.com/ysb33r/grysb33r' }
  } 
  dependencies {
    classpath 'org.ysb33r.gradle:gnumake:0.0.9'
  }
}

import org.ysb33r.gradle.gnumake.GnuMakeBuild

task runMake (type:GnuMakeBuild) {
    targets = ['build','install']
    flags = [ DESTDIR : '/copy/files/here', BUILD_NUMBER : 12345 ]
}
```

**Comment by ysb33r** [comment]
There might be an issue with 1.11. I'll check that out.

Thanks.

## 

Schalk W. Cronjé
[Sent from mobile phone]

<div>-------- Original message --------</div><div>From: Andres Almiray notifications@github.com </div><div>Date:05/03/2014  21:20  (GMT+00:00) </div><div>To: aalmiray/gradle-plugins gradle-plugins@noreply.github.com </div><div>Cc: "Schalk W. Cronjé" yw-github@af.org.za </div><div>Subject: Re: [gradle-plugins] Add GnuMake plugin (#65) </div><div>
</div>So just to be on the same page, this is what I tried

buildscript {
  repositories {
    ivy { url 'http://dl.bintray.com/ysb33r/grysb33r' }
  } 
  dependencies {
    classpath 'org.ysb33r.gradle:gnumake:0.0.9'
  }
}

import org.ysb33r.gradle.gnumake.GnuMakeBuild

task runMake (type:GnuMakeBuild) {
    targets = ['build','install']
    flags = [ DESTDIR : '/copy/files/here', BUILD_NUMBER : 12345 ]
}

**Comment by mustajarvi** [comment]
Change

```
repositories {
    ivy { url 'http://dl.bintray.com/ysb33r/grysb33r' }
}
```

to

```
repositories {
    maven { url 'http://dl.bintray.com/ysb33r/grysb33r' }
}
```

and it seems to work.
